package githubchange

import (
	"context"
	"crypto/sha1"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/NDDev-OpenNetwork/github-device-sync/core/operations"
	githubprovider "github.com/NDDev-OpenNetwork/github-device-sync/core/providers/github"
	"github.com/NDDev-OpenNetwork/github-device-sync/core/validation"
)

type fixtureFile struct {
	sha     string
	content []byte
}

type changeFixture struct {
	scope    githubprovider.RepositoryMutationScope
	branches map[string]string
	files    map[string]map[string]fixtureFile
	pulls    []githubprovider.DraftPullRequest
	writes   int
}

func TestHandlerAppliesAndVerifiesExactMultiFileDraftPR(t *testing.T) {
	fixture := newChangeFixture()
	baseSHA := fixture.branches["main"]
	files := []PlannedFile{
		{Path: ".github/workflows/gds.yml", Status: "added", ContentDigest: DigestContent([]byte("name: gds\n"))},
		{Path: "AGENTS.md", Status: "modified", ContentDigest: DigestContent([]byte("generated\n"))},
	}
	scope := Scope{
		ReadInstallationID: "installation:read", MutationCapabilityID: "mutation:write",
		ProviderRepositoryID: 42, Owner: "example", Name: "repository",
		BaseBranch: "main", BaseSHA: baseSHA, HeadBranch: "gds/change",
	}
	changeDigest, err := ChangeSetDigest(scope, files)
	if err != nil {
		t.Fatal(err)
	}
	scope.ChangeSetDigest = changeDigest
	steps := []operations.Step{
		changeStep("branch", BranchAction, OperationParameters{
			Scope: scope, Branch: &BranchChange{ExpectedState: "missing", TargetSHA: baseSHA},
		}),
		changeStep("workflow", ContentAction, OperationParameters{
			Scope: scope, Content: encodedContent(
				".github/workflows/gds.yml", "missing", "", "added", []byte("name: gds\n"),
			),
		}),
		changeStep("agents", ContentAction, OperationParameters{
			Scope: scope, Content: encodedContent(
				"AGENTS.md", "regular", fixture.files["main"]["AGENTS.md"].sha,
				"modified", []byte("generated\n"),
			),
		}),
		changeStep("pull-request", DraftPRAction, OperationParameters{
			Scope: scope, PullRequest: &PullRequestChange{
				Title: "chore: update GDS projections", Body: "Generated by GDS.", Files: files,
			},
		}),
	}
	schemas, err := validation.NewSchemaSet()
	if err != nil {
		t.Fatal(err)
	}
	now := time.Date(2026, 7, 11, 5, 0, 0, 0, time.UTC)
	plan, err := operations.NewPlan(
		"plan_01KX7BV07RHD6KRA4Z4J0KCHGR", now, now.Add(15*time.Minute),
		operations.PlanInput{
			Operation: "publish-github-change",
			Actor:     operations.Actor{Type: "agent-session", SessionID: "test-session"},
			Preconditions: []operations.Precondition{{
				RepositoryID: "repo_01JEXAMPZ0000000000000000C", HeadOID: baseSHA,
				ManifestDigest: "sha256:" + strings.Repeat("a", 64),
				PolicyDigest:   "sha256:" + strings.Repeat("b", 64),
			}},
			Steps: steps, ApprovalClass: "github-change-write",
		},
	)
	if err != nil || len(plan.Validate(schemas)) != 0 {
		t.Fatalf("plan err=%v findings=%#v", err, plan.Validate(schemas))
	}
	if err := ValidatePlan(plan); err != nil {
		t.Fatal(err)
	}
	evidence := make([]any, len(steps))
	for index, step := range steps {
		handler := &Handler{Reader: fixture, Writer: fixture, Action: step.Action}
		result, err := handler.Apply(context.Background(), step)
		if err != nil {
			t.Fatalf("apply %s: %v", step.Action, err)
		}
		evidence[index] = result.After
	}
	if fixture.writes != 4 || len(fixture.pulls) != 1 {
		t.Fatalf("writes=%d pulls=%d", fixture.writes, len(fixture.pulls))
	}
	for index, step := range steps {
		handler := &Handler{Reader: fixture, Scope: fixture.scope, Action: step.Action}
		raw := mustJSON(t, evidence[index])
		if err := handler.Verify(context.Background(), step, raw); err != nil {
			t.Fatalf("verify %s: %v", step.Action, err)
		}
	}
}

func TestHandlerBlocksStaleContentWithoutWrite(t *testing.T) {
	fixture := newChangeFixture()
	scope := Scope{
		ReadInstallationID: "installation:read", MutationCapabilityID: "mutation:write",
		ProviderRepositoryID: 42, Owner: "example", Name: "repository",
		BaseBranch: "main", BaseSHA: fixture.branches["main"], HeadBranch: "gds/change",
	}
	scope.ChangeSetDigest = "sha256:" + strings.Repeat("a", 64)
	fixture.branches[scope.HeadBranch] = scope.BaseSHA
	fixture.files[scope.HeadBranch] = cloneFiles(fixture.files["main"])
	change := encodedContent("AGENTS.md", "regular", strings.Repeat("f", 40), "modified", []byte("generated\n"))
	step := changeStep("agents", ContentAction, OperationParameters{Scope: scope, Content: change})
	handler := &Handler{Reader: fixture, Writer: fixture, Action: ContentAction}
	if _, err := handler.Apply(context.Background(), step); err == nil || fixture.writes != 0 {
		t.Fatalf("err=%v writes=%d", err, fixture.writes)
	}
}

func TestValidatePlanRejectsPullRequestFileMismatch(t *testing.T) {
	fixture := newChangeFixture()
	scope := Scope{
		ReadInstallationID: "installation:read", MutationCapabilityID: "mutation:write",
		ProviderRepositoryID: 42, Owner: "example", Name: "repository",
		ChangeSetDigest: "sha256:" + strings.Repeat("a", 64), BaseBranch: "main",
		BaseSHA: fixture.branches["main"], HeadBranch: "gds/change",
	}
	plan := operations.Plan{Steps: []operations.Step{
		changeStep("branch", BranchAction, OperationParameters{Scope: scope, Branch: &BranchChange{ExpectedState: "missing", TargetSHA: scope.BaseSHA}}),
		changeStep("agents", ContentAction, OperationParameters{Scope: scope, Content: encodedContent("AGENTS.md", "regular", fixture.files["main"]["AGENTS.md"].sha, "modified", []byte("generated\n"))}),
		changeStep("pull", DraftPRAction, OperationParameters{Scope: scope, PullRequest: &PullRequestChange{
			Title: "Title", Body: "Body", Files: []PlannedFile{{Path: "other.md", Status: "modified", ContentDigest: DigestContent([]byte("generated\n"))}},
		}}),
	}}
	if err := ValidatePlan(plan); err == nil {
		t.Fatal("mismatched pull-request file contract was accepted")
	}
}

func TestBuildPreservesBaseRelativeStatusForIdempotentReplan(t *testing.T) {
	baseSHA := strings.Repeat("a", 40)
	result, err := Build(BuildInput{
		RepositoryID: "repo_01JEXAMPZ0000000000000000C",
		Scope: Scope{
			ReadInstallationID: "installation:read", MutationCapabilityID: "mutation:write",
			ProviderRepositoryID: 42, Owner: "example", Name: "repository",
			BaseBranch: "main", BaseSHA: baseSHA, HeadBranch: "gds/change",
		},
		Branch: BranchChange{
			ExpectedState: "present", ExpectedSHA: strings.Repeat("b", 40),
			TargetSHA: strings.Repeat("b", 40),
		},
		Title: "chore: update GDS projections",
		Body:  "Generated by GDS.",
		Files: []ContentInput{{
			Path: ".gds/bundle.lock.yaml", Message: "chore: update GDS projections",
			ExpectedState: "regular", ExpectedSHA: strings.Repeat("c", 40),
			Content: []byte("generated\n"), FinalStatus: "added",
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	content, err := StepParameters(result.Steps[1])
	if err != nil || content.Content == nil || content.Content.FinalStatus != "added" {
		t.Fatalf("content=%#v err=%v", content.Content, err)
	}
	if result.Files[0].Status != "added" {
		t.Fatalf("planned status=%q", result.Files[0].Status)
	}
	if err := ValidatePlan(operations.Plan{Steps: result.Steps}); err != nil {
		t.Fatal(err)
	}
}

func TestPrepareBuildsExactProjectionChangeFromObservedBranches(t *testing.T) {
	fixture := newChangeFixture()
	prepared, err := Prepare(context.Background(), fixture, PrepareInput{
		RepositoryID:       "repo_01JEXAMPZ0000000000000000C",
		ReadInstallationID: "installation:read", MutationCapabilityID: "mutation:write",
		ProviderRepositoryID: 42, Owner: "example", Name: "repository",
		BaseBranch: "main", HeadBranch: "gds/projection-abc",
		Title: "chore: update GDS projections", Body: "Generated by GDS.",
		Files: []DesiredFile{
			{Path: "AGENTS.md", Message: "chore: update GDS projections", Content: []byte("old\n")},
			{Path: ".gds/bundle.lock.yaml", Message: "chore: update GDS projections", Content: []byte("lock\n")},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	if prepared.NoChanges || len(prepared.Build.Files) != 1 || prepared.Build.Files[0].Status != "added" ||
		prepared.Build.Files[0].Path != ".gds/bundle.lock.yaml" || prepared.EvidenceDigest == "" {
		t.Fatalf("prepared=%#v", prepared)
	}
	parameters, err := StepParameters(prepared.Build.Steps[1])
	if err != nil || parameters.Content.ExpectedState != "missing" || parameters.Content.FinalStatus != "added" {
		t.Fatalf("content=%#v err=%v", parameters.Content, err)
	}
}

func TestPreparePreservesAddedStatusWhenDesiredContentAlreadyExistsOnHead(t *testing.T) {
	fixture := newChangeFixture()
	head := "gds/projection-abc"
	fixture.branches[head] = strings.Repeat("b", 40)
	fixture.files[head] = cloneFiles(fixture.files["main"])
	fixture.files[head][".gds/bundle.lock.yaml"] = fileState([]byte("lock\n"))
	fixture.writes = 1
	prepared, err := Prepare(context.Background(), fixture, PrepareInput{
		RepositoryID:       "repo_01JEXAMPZ0000000000000000C",
		ReadInstallationID: "installation:read", MutationCapabilityID: "mutation:write",
		ProviderRepositoryID: 42, Owner: "example", Name: "repository",
		BaseBranch: "main", HeadBranch: head,
		Title: "chore: update GDS projections", Body: "Generated by GDS.",
		Files: []DesiredFile{{
			Path: ".gds/bundle.lock.yaml", Message: "chore: update GDS projections", Content: []byte("lock\n"),
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	parameters, err := StepParameters(prepared.Build.Steps[1])
	if err != nil || parameters.Content.ExpectedState != "regular" || parameters.Content.FinalStatus != "added" {
		t.Fatalf("content=%#v err=%v", parameters.Content, err)
	}
}

func TestObserveInitialRejectsUnexpectedExistingBranchFile(t *testing.T) {
	fixture := newChangeFixture()
	head := "gds/projection-abc"
	fixture.branches[head] = strings.Repeat("b", 40)
	fixture.files[head] = cloneFiles(fixture.files["main"])
	fixture.files[head]["unexpected.txt"] = fileState([]byte("unexpected\n"))
	fixture.writes = 1
	_, err := Prepare(context.Background(), fixture, PrepareInput{
		RepositoryID:       "repo_01JEXAMPZ0000000000000000C",
		ReadInstallationID: "installation:read", MutationCapabilityID: "mutation:write",
		ProviderRepositoryID: 42, Owner: "example", Name: "repository",
		BaseBranch: "main", HeadBranch: head,
		Title: "chore: update GDS projections", Body: "Generated by GDS.",
		Files: []DesiredFile{{
			Path: "AGENTS.md", Message: "chore: update GDS projections", Content: []byte("generated\n"),
		}},
	})
	if err == nil || !strings.Contains(err.Error(), "unexpected file") {
		t.Fatalf("err=%v", err)
	}
}

func newChangeFixture() *changeFixture {
	baseSHA := strings.Repeat("a", 40)
	return &changeFixture{
		scope: githubprovider.RepositoryMutationScope{
			RepositoryID: 42, Owner: "example", Name: "repository",
			Operations: []string{githubprovider.MutationBranch, githubprovider.MutationPullRequest, githubprovider.MutationWorkflowCaller},
		},
		branches: map[string]string{"main": baseSHA},
		files: map[string]map[string]fixtureFile{
			"main": {"AGENTS.md": fileState([]byte("old\n"))},
		},
	}
}

func (fixture *changeFixture) Scope() githubprovider.RepositoryMutationScope {
	return fixture.scope
}

func (fixture *changeFixture) GetBranchRef(
	_ context.Context, owner string, name string, branch string,
) (githubprovider.RefResult, githubprovider.ResponseMeta, error) {
	if owner != fixture.scope.Owner || name != fixture.scope.Name {
		return githubprovider.RefResult{}, githubprovider.ResponseMeta{}, fmt.Errorf("scope mismatch")
	}
	sha, found := fixture.branches[branch]
	if !found {
		return githubprovider.RefResult{}, githubprovider.ResponseMeta{}, absentError()
	}
	return githubprovider.RefResult{Ref: "refs/heads/" + branch, SHA: sha}, githubprovider.ResponseMeta{}, nil
}

func (fixture *changeFixture) GetContent(
	_ context.Context, owner string, name string, path string, ref string,
) (githubprovider.ContentState, githubprovider.ResponseMeta, error) {
	if owner != fixture.scope.Owner || name != fixture.scope.Name {
		return githubprovider.ContentState{}, githubprovider.ResponseMeta{}, fmt.Errorf("scope mismatch")
	}
	file, found := fixture.files[ref][path]
	if !found {
		return githubprovider.ContentState{}, githubprovider.ResponseMeta{}, absentError()
	}
	return githubprovider.ContentState{Path: path, BlobSHA: file.sha, Content: append([]byte(nil), file.content...)}, githubprovider.ResponseMeta{}, nil
}

func (fixture *changeFixture) CompareBranches(
	_ context.Context, owner string, name string, base string, head string,
) (githubprovider.BranchComparison, githubprovider.ResponseMeta, error) {
	if owner != fixture.scope.Owner || name != fixture.scope.Name {
		return githubprovider.BranchComparison{}, githubprovider.ResponseMeta{}, fmt.Errorf("scope mismatch")
	}
	baseFiles := fixture.files[base]
	headFiles := fixture.files[head]
	paths := make([]string, 0)
	for path, headFile := range headFiles {
		baseFile, found := baseFiles[path]
		if !found || baseFile.sha != headFile.sha {
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)
	files := make([]githubprovider.ComparisonFile, len(paths))
	for index, path := range paths {
		status := "modified"
		if _, found := baseFiles[path]; !found {
			status = "added"
		}
		files[index] = githubprovider.ComparisonFile{Path: path, Status: status, BlobSHA: headFiles[path].sha}
	}
	return githubprovider.BranchComparison{
		Status: "ahead", AheadBy: fixture.writes - len(fixture.pulls), BehindBy: 0,
		TotalCommits: fixture.writes - len(fixture.pulls), BaseSHA: fixture.branches[base],
		HeadSHA: fixture.branches[head], MergeBaseSHA: fixture.branches[base], Files: files,
	}, githubprovider.ResponseMeta{}, nil
}

func (fixture *changeFixture) ListOpenPullRequests(
	_ context.Context, owner string, name string, head string, base string,
) ([]githubprovider.DraftPullRequest, githubprovider.ResponseMeta, error) {
	if owner != fixture.scope.Owner || name != fixture.scope.Name {
		return nil, githubprovider.ResponseMeta{}, fmt.Errorf("scope mismatch")
	}
	return append([]githubprovider.DraftPullRequest(nil), fixture.pulls...), githubprovider.ResponseMeta{}, nil
}

func (fixture *changeFixture) CreateBranch(
	_ context.Context, branch string, fromSHA string,
) (githubprovider.RefResult, githubprovider.MutationMeta, error) {
	if _, exists := fixture.branches[branch]; exists || fixture.branches["main"] != fromSHA {
		return githubprovider.RefResult{}, githubprovider.MutationMeta{}, fmt.Errorf("branch create precondition")
	}
	fixture.branches[branch] = fromSHA
	fixture.files[branch] = cloneFiles(fixture.files["main"])
	fixture.writes++
	return githubprovider.RefResult{Ref: "refs/heads/" + branch, SHA: fromSHA}, fixture.meta(), nil
}

func (fixture *changeFixture) FastForwardBranch(
	_ context.Context, branch string, target string,
) (githubprovider.RefResult, githubprovider.MutationMeta, error) {
	if _, exists := fixture.branches[branch]; !exists {
		return githubprovider.RefResult{}, githubprovider.MutationMeta{}, fmt.Errorf("branch missing")
	}
	fixture.branches[branch] = target
	fixture.writes++
	return githubprovider.RefResult{Ref: "refs/heads/" + branch, SHA: target}, fixture.meta(), nil
}

func (fixture *changeFixture) PutContent(
	_ context.Context, update githubprovider.ContentUpdate,
) (githubprovider.ContentResult, githubprovider.MutationMeta, error) {
	current, found := fixture.files[update.Branch][update.Path]
	if update.ExpectedSHA != "" && (!found || current.sha != update.ExpectedSHA) {
		return githubprovider.ContentResult{}, githubprovider.MutationMeta{}, fmt.Errorf("content precondition")
	}
	file := fileState(update.Content)
	fixture.files[update.Branch][update.Path] = file
	fixture.writes++
	commitSHA := oid(fmt.Sprintf("commit-%d", fixture.writes))
	fixture.branches[update.Branch] = commitSHA
	return githubprovider.ContentResult{Path: update.Path, BlobSHA: file.sha, CommitSHA: commitSHA}, fixture.meta(), nil
}

func (fixture *changeFixture) CreateDraftPullRequest(
	_ context.Context, title string, body string, head string, base string,
) (githubprovider.DraftPullRequest, githubprovider.MutationMeta, error) {
	fixture.writes++
	pull := githubprovider.DraftPullRequest{
		Number: 1, ID: 2, HTMLURL: "https://github.com/example/repository/pull/1",
		HeadRef: head, HeadSHA: fixture.branches[head], BaseRef: base,
		Draft: true, State: "open", Title: title, Body: body,
	}
	fixture.pulls = []githubprovider.DraftPullRequest{pull}
	return pull, fixture.meta(), nil
}

func (fixture *changeFixture) meta() githubprovider.MutationMeta {
	return githubprovider.MutationMeta{RepositoryID: 42, StatusCode: 200, RequestID: "fixture"}
}

func encodedContent(path, state, expected, finalStatus string, content []byte) *ContentChange {
	return &ContentChange{
		Path: path, Message: "chore: update " + path, ExpectedState: state,
		ExpectedSHA: expected, FinalStatus: finalStatus,
		ContentBase64: base64.StdEncoding.EncodeToString(content),
		ContentDigest: DigestContent(content),
	}
}

func changeStep(id, action string, parameters OperationParameters) operations.Step {
	return operations.Step{
		StepID: id, RepositoryID: "repo_01JEXAMPZ0000000000000000C", Action: action,
		RequiresApproval: true, Compensation: operations.Compensation{Mode: "manual"},
		Parameters: Parameters(parameters),
	}
}

func fileState(content []byte) fixtureFile {
	return fixtureFile{sha: oid("blob\x00" + string(content)), content: append([]byte(nil), content...)}
}

func cloneFiles(values map[string]fixtureFile) map[string]fixtureFile {
	result := make(map[string]fixtureFile, len(values))
	for path, file := range values {
		result[path] = fixtureFile{sha: file.sha, content: append([]byte(nil), file.content...)}
	}
	return result
}

func oid(value string) string {
	digest := sha1.Sum([]byte(value))
	return fmt.Sprintf("%x", digest[:])
}

func absentError() error {
	return &githubprovider.APIError{Kind: githubprovider.ErrorNotFoundOrInaccessible, StatusCode: 404}
}

func mustJSON(t *testing.T, value any) []byte {
	t.Helper()
	raw, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	return raw
}
