#!/usr/bin/env python3
"""Generate docs/adr/README.md — the ADR index and supersession graph.

Each ADR declares its own `Status:`, and optionally `Supersedes:` /
`Superseded in part by:` / `Superseded by:` lines directly under it. This script
reads those declarations and renders one table, so a reader never has to hold
mutually exclusive decisions in their head to work out which one is normative.

Run with `--check` to fail when the committed index is stale.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADR_DIR = ROOT / "docs" / "adr"
INDEX = ADR_DIR / "README.md"

HEADER = """<!-- Generated by scripts/generate_adr_index.py. Do not edit by hand. -->

# Architecture decision index

Every accepted decision, newest first, with its supersession relationships. A
decision that is superseded in part keeps its historical context: only the named
clause stops being normative.

| ADR | Title | Status | Supersedes | Superseded by |
|---|---|---|---|---|
"""

# A relation declaration is a paragraph, not a line: it runs to the next blank
# line. Matching `(.+)$` captured the first physical line only, so a wrapped
# declaration reached the index truncated mid-sentence — and the index is the
# normative supersession graph, so a reader could not tell which clause stopped
# applying.
RELATION_PATTERNS = {
    "supersedes": re.compile(
        r"^Supersedes:[ \t]*(.+?)(?=\n[ \t]*\n|\n#|\Z)", re.MULTILINE | re.DOTALL
    ),
    "superseded": re.compile(
        r"^Superseded(?P<partial> in part)? by:[ \t]*(?P<body>.+?)(?=\n[ \t]*\n|\n#|\Z)",
        re.MULTILINE | re.DOTALL,
    ),
}
ADR_REFERENCE = re.compile(r"ADR\s*(\d{4})")


def relation_targets(declaration: str, partial: bool) -> str:
    """Reduce a free-prose relation declaration to the ADR graph edge it states.

    The index answers one question — which decision replaced which — so it names
    ADR ids rather than repeating the sentence. That also keeps the generated
    index free of subjects that no longer exist: a retired module names itself in
    the ADR body, where the history belongs, and not in the current-state index.
    """
    numbers = sorted(set(ADR_REFERENCE.findall(declaration)))
    if not numbers:
        return "—"
    suffix = " (in part)" if partial else ""
    return ", ".join(f"ADR {number}" for number in numbers) + suffix


def render() -> str:
    known: set[str] = set()
    for path in ADR_DIR.glob("[0-9][0-9][0-9][0-9]-*.md"):
        known.add(path.name[:4])
    rows: list[tuple[str, str]] = []
    unknown: list[str] = []
    for path in sorted(ADR_DIR.glob("[0-9][0-9][0-9][0-9]-*.md"), reverse=True):
        text = path.read_text(encoding="utf-8")
        title_match = re.search(r"^#\s*ADR\s*(\d{4}):\s*(.+)$", text, re.MULTILINE)
        if title_match is None:
            continue
        number, title = title_match.group(1), title_match.group(2).strip()
        status_match = re.search(r"^Status:\s*(.+)$", text, re.MULTILINE)
        status = status_match.group(1).strip() if status_match else "Unknown"
        supersedes_match = RELATION_PATTERNS["supersedes"].search(text)
        superseded_match = RELATION_PATTERNS["superseded"].search(text)
        supersedes = (
            relation_targets(supersedes_match.group(1), False)
            if supersedes_match
            else "—"
        )
        superseded = (
            relation_targets(
                superseded_match.group("body"), bool(superseded_match.group("partial"))
            )
            if superseded_match
            else "—"
        )
        for cell in (supersedes, superseded):
            for referenced in ADR_REFERENCE.findall(cell):
                if referenced not in known:
                    unknown.append(f"ADR {number} references missing ADR {referenced}")
        rows.append(
            (
                number,
                f"| [{number}]({path.name}) | {title} | {status} | "
                f"{supersedes} | {superseded} |",
            )
        )
    if unknown:
        for problem in sorted(set(unknown)):
            print(problem, file=sys.stderr)
        raise SystemExit(1)
    return HEADER + "\n".join(row for _, row in rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render()
    if arguments.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.is_file() else ""
        if current != rendered:
            print(
                "docs/adr/README.md is stale; run scripts/generate_adr_index.py",
                file=sys.stderr,
            )
            return 1
        print("ADR index: current")
        return 0
    INDEX.write_text(rendered, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
