name: CI feedback

on:
  workflow_run:
    workflows: [gds-ci]
    types: [completed]

permissions:
  actions: read
  issues: write

jobs:
  feedback:
    if: ${{ contains(fromJSON('["failure","timed_out","action_required","stale","startup_failure","cancelled"]'), github.event.workflow_run.conclusion) }}
    uses: NDDev-OpenNetwork/github-actions/.github/workflows/ci-feedback.yml@a0dc5592333dcfdf2a3d239ed1f2b128899e5482
    with:
      run-id: ${{ format('{0}', github.event.workflow_run.id) }}
      run-attempt: ${{ format('{0}', github.event.workflow_run.run_attempt) }}
