name: CI feedback

on:
  workflow_run:
    workflows: [gds-ci]
    types: [completed]

permissions:
  actions: read
  issues: write

jobs:
  feedback:
    if: ${{ contains(fromJSON('["failure","timed_out","action_required","stale","startup_failure"]'), github.event.workflow_run.conclusion) }}
    uses: NDDev-OpenNetwork/github-actions/.github/workflows/ci-feedback.yml@5fd7da9ab8e29c26a41e14bc9c8d5b101ce4bd06
    with:
      run-id: ${{ format('{0}', github.event.workflow_run.id) }}
      run-attempt: ${{ format('{0}', github.event.workflow_run.run_attempt) }}
